---
- name: generate locale
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - zh_TW.UTF-8

- name: setup locale configuation
  copy: src=locale dest=/etc/default/locale
