---
- name: add postgresql repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5' state=present
  register: result

- name: add postgresql key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: update apt cache
  apt: update_cache=yes
  when: result|changed
